const DEPARTMENT_VALUES = [
  "DIGITAL BUSINESS TECHNOLOGY",
  "ARTIFICIAL INTELIGENCE AND ROBOTIC",
  "BUSINESS MATHEMATICS",
  "FOOD BUSINESS TECHNOLOGY",
  "PRODUCT DESIGN AND INNOVATION",
  "ENERGY BUSINESS AND TECHNOLOGY",
];

const DEPARTMENT_OPTIONS = DEPARTMENT_VALUES.map((value) => ({
  value,
  label: value,
}));

export { DEPARTMENT_VALUES, DEPARTMENT_OPTIONS };

