const DEPARTMENT_VALUES = [
  "DIGITAL BUSINESS TECHNOLOGY",
  "ARTIFICIAL INTELIGENCE AND ROBOTIC",
  "BUSINESS MATHEMATICS",
  "FOOD BUSINESS TECHNOLOGY",
  "PRODUCT DESIGN AND INNOVATION",
  "ENERGY BUSINESS AND TECHNOLOGY",
];

const DEPARTMENT_LABELS = {
  [DEPARTMENT_VALUES[0]]: "Digital Business Technology",
  [DEPARTMENT_VALUES[1]]: "Artificial Inteligence and Robotic",
  [DEPARTMENT_VALUES[2]]: "Business Mathematics",
  [DEPARTMENT_VALUES[3]]: "Food Business Technology",
  [DEPARTMENT_VALUES[4]]: "Product Design and Innovation",
  [DEPARTMENT_VALUES[5]]: "Energy Business and Technology",
};

const DEPARTMENT_OPTIONS = DEPARTMENT_VALUES.map((value) => ({
  value,
  label: DEPARTMENT_LABELS[value] || value,
}));

const DEPARTMENT_FILTER_OPTIONS = Object.values(DEPARTMENT_LABELS);

export {
  DEPARTMENT_VALUES,
  DEPARTMENT_LABELS,
  DEPARTMENT_OPTIONS,
  DEPARTMENT_FILTER_OPTIONS,
};
