# Generated by Django 4.2.27 on 2026-01-24 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0002_profile_department_profile_id_number_profile_role'),
        ('csluse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_created_by', to='csluse_auth.profile'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('number', models.CharField(max_length=4)),
                ('floor', models.CharField(max_length=4)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csluse.image')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_pic_by', to='csluse_auth.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('broken', 'Broken'), ('storage', 'In Storage')], default='available', max_length=20)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('electronics', 'Electronics'), ('large_equipment', 'Large Equipment'), ('furniture', 'Furniture'), ('glassware', 'Glassware'), ('chemicals', 'Chemicals'), ('tools', 'Tools'), ('safety', 'Safety Equipment'), ('other', 'Other')], default='other', max_length=20)),
                ('is_moveable', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csluse.image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='csluse.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('end_time_actual', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('class', 'Class'), ('lab_work', 'Lab Work'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost_damaged', 'Lost/Damaged'), ('cancelled', 'Cancelled')], default='borrowed', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_borrows', to='csluse_auth.profile')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='csluse.equipment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='csluse_auth.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_equipment', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, max_length=2000, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to='csluse_auth.profile')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_bookings', to='csluse.equipment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='csluse_auth.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='csluse.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
