# Generated by Django 4.2.27 on 2026-01-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csluse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='s3upload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
