# Generated by Django 4.2.27 on 2026-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0002_alter_image_created_by_room_equipment_borrow_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
