# Generated by Django 4.2.27 on 2026-01-29 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0004_alter_profile_department_alter_profile_role_and_more'),
        ('csluse', '0003_alter_room_floor_alter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reminder', 'Reminder'), ('general', 'General')], default='general', max_length=255)),
                ('message', models.CharField(max_length=2000)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='csluse_auth.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
