# Generated by Django 4.2.27 on 2026-02-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0005_add_booking_borrow_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('class', 'Class'), ('lab_work', 'Lab Work'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='code',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
    ]
