# Generated by Django 4.2.27 on 2026-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0007_alter_equipment_quantity_use_structureorganization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('Class', 'Class'), ('Lab Work', 'Lab Work'), ('Research', 'Research'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='purpose',
            field=models.CharField(choices=[('Class', 'Class'), ('Lab Work', 'Lab Work'), ('Research', 'Research'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Lost/Damaged', 'Lost/Damaged'), ('Cancelled', 'Cancelled')], default='Borrowed', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Electronics', 'Electronics'), ('Large Equipment', 'Large Equipment'), ('Furniture', 'Furniture'), ('Glassware', 'Glassware'), ('Chemicals', 'Chemicals'), ('Tools', 'Tools'), ('Safety Equipment', 'Safety Equipment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Under Maintenance', 'Under Maintenance'), ('Broken', 'Broken'), ('In Storage', 'In Storage')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Reminder', 'Reminder'), ('General', 'General')], default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='use',
            name='purpose',
            field=models.CharField(choices=[('Class', 'Class'), ('Lab Work', 'Lab Work'), ('Research', 'Research'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='use',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Use', 'In Use'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
