# Generated by Django 4.2.27 on 2026-03-14 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0006_replace_other_role_with_guest'),
        ('csluse', '0008_alter_booking_purpose_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengujian',
            name='sample_condition',
        ),
        migrations.RemoveField(
            model_name='pengujian',
            name='sample_shape',
        ),
        migrations.AddField(
            model_name='pengujian',
            name='sample_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pengujian',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=5000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs_created_by', to='csluse_auth.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
