# Generated by Django 4.2.27 on 2026-03-14 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0006_replace_other_role_with_guest'),
        ('csluse', '0009_remove_pengujian_sample_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('category', models.CharField(choices=[('Practicum', 'Practicum'), ('Maintenance', 'Maintenance'), ('Agenda', 'Agenda'), ('Holiday', 'Holiday'), ('Block', 'Block'), ('Other', 'Other')], default='Other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created_by', to='csluse_auth.profile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='csluse.room')),
            ],
            options={
                'ordering': ['start_time', 'title'],
            },
        ),
    ]
