# Generated by Django 4.2.27 on 2026-03-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0010_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
    ]
