# Generated by Django 4.2.27 on 2026-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0006_replace_other_role_with_guest'),
        ('csluse', '0011_remove_announcement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pic',
        ),
        migrations.AddField(
            model_name='room',
            name='pics',
            field=models.ManyToManyField(blank=True, related_name='rooms_as_pic', to='csluse_auth.profile'),
        ),
        migrations.DeleteModel(
            name='LabProfile',
        ),
    ]
