# Generated by Django 4.2.27 on 2026-03-18 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0012_remove_room_pic_room_pics_delete_labprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='quantity_equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='attendee_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='attendee_names',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Lost/Damaged', 'Lost/Damaged')], default='Borrowed', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='use',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Use', 'In Use'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingEquipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='csluse.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='csluse.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
