# Generated by Django 4.2.27 on 2026-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0013_remove_booking_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('In Use', 'In Use'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
