# Generated by Django 4.2.27 on 2026-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0014_alter_use_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
