# Generated by Django 4.2.27 on 2026-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0015_alter_use_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Completed', 'Completed')], default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Borrowed', 'Borrowed'), ('Returned Pending Inspection', 'Returned Pending Inspection'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Lost/Damaged', 'Lost/Damaged')], default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='use',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Completed', 'Completed')], default='Pending', max_length=32),
        ),
    ]
