# Generated by Django 4.2.27 on 2026-03-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0016_alter_booking_status_alter_borrow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='inspection_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
