# Generated by Django 4.2.27 on 2026-03-31 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0018_remove_schedule_is_active_booking_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='institution_address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requester_mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='workshop_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='workshop_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='workshop_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='institution_address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='requester_mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='institution_address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='requester_mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('Thesis', 'Skripsi/TA'), ('Practicum', 'Praktikum'), ('Research', 'Penelitian'), ('Workshop', 'Workshop')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='purpose',
            field=models.CharField(choices=[('Thesis', 'Skripsi/TA'), ('Practicum', 'Praktikum'), ('Research', 'Penelitian'), ('Workshop', 'Workshop')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='use',
            name='purpose',
            field=models.CharField(choices=[('Thesis', 'Skripsi/TA'), ('Practicum', 'Praktikum'), ('Research', 'Penelitian'), ('Workshop', 'Workshop')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('license_info', models.CharField(blank=True, max_length=255, null=True)),
                ('license_expiration', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='csluse.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
