# Generated by Django 4.2.27 on 2026-03-31 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0019_booking_institution_booking_institution_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='room',
        ),
        migrations.AddField(
            model_name='software',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='csluse.equipment'),
            preserve_default=False,
        ),
    ]
