# Generated by Django 4.2.27 on 2026-03-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0020_remove_software_room_software_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Electronics', 'Electronics'), ('Computer', 'Computer'), ('Large Equipment', 'Large Equipment'), ('Furniture', 'Furniture'), ('Glassware', 'Glassware'), ('Chemicals', 'Chemicals'), ('Tools', 'Tools'), ('Safety Equipment', 'Safety Equipment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.CharField(choices=[('Practicum', 'Praktikum')], default='Practicum', max_length=20),
        ),
    ]
