# Generated by Django 4.2.27 on 2026-03-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0021_alter_equipment_category_alter_schedule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
