# Generated by Django 4.2.27 on 2026-03-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0022_schedule_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='rejection_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='rejection_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
