# Generated by Django 4.2.27 on 2026-03-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0023_booking_rejection_note_borrow_rejection_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('Skripsi/TA', 'Skripsi/TA'), ('Praktikum', 'Praktikum'), ('Penelitian', 'Penelitian'), ('Workshop', 'Workshop')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='purpose',
            field=models.CharField(choices=[('Skripsi/TA', 'Skripsi/TA'), ('Praktikum', 'Praktikum'), ('Penelitian', 'Penelitian'), ('Workshop', 'Workshop')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='use',
            name='purpose',
            field=models.CharField(choices=[('Skripsi/TA', 'Skripsi/TA'), ('Praktikum', 'Praktikum'), ('Penelitian', 'Penelitian'), ('Workshop', 'Workshop')], default='Other', max_length=20),
        ),
    ]
