# Generated by Django 4.2.27 on 2026-03-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0024_alter_booking_purpose_alter_borrow_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='csluse.room'),
        ),
        migrations.AlterField(
            model_name='software',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='csluse.equipment'),
        ),
    ]
