# Generated by Django 4.2.27 on 2026-04-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0025_alter_equipment_room_alter_software_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
