# Generated by Django 4.2.27 on 2026-04-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0027_delete_structureorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='csluse.image'),
        ),
    ]
