# Generated by Django 4.2.27 on 2026-04-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0009_profile_is_mentor'),
        ('csluse', '0029_remove_staff_from_room_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_approved_by_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requester_mentor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bookings_as_mentor', to='csluse_auth.profile'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_approved_by_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='mentor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='requester_mentor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_borrows_as_mentor', to='csluse_auth.profile'),
        ),
        migrations.AddField(
            model_name='use',
            name='is_approved_by_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='use',
            name='mentor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='requester_mentor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_uses_as_mentor', to='csluse_auth.profile'),
        ),
    ]
