# Generated by Django 4.2.27 on 2026-04-05 23:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0009_profile_is_mentor'),
        ('csluse', '0030_booking_is_approved_by_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengujian',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Diproses', 'Diproses'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='documents/sample-testing/')),
                ('document_type', models.CharField(choices=[('testing_agreement', 'Surat perjanjian pengujian'), ('signed_testing_agreement', 'Surat perjanjian pengujian yang sudah ditandatangani'), ('invoice', 'Invoice'), ('payment_proof', 'Bukti bayar'), ('test_result_letter', 'Surat hasil uji')], max_length=64)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('pengujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='csluse.pengujian')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='csluse_auth.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('pengujian', 'document_type'), name='unique_pengujian_document_type'),
        ),
    ]
