# Generated by Django 4.2.27 on 2026-01-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('digital business technology', 'Digital Business Technology'), ('artificial inteligence and robotic', 'Artificial Inteligence and Robotic'), ('business mathematics', 'Business Mathematics'), ('food business technology', 'Food Business Technology'), ('product design and innovation', 'Product Design and Innovation'), ('energy business and technology', 'Energy Business and Technology')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Admin'), ('staff', 'Staff'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
