# Generated by Django 4.2.27 on 2026-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0002_profile_department_profile_id_number_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=4, null=True),
        ),
    ]
