# Generated by Django 4.2.27 on 2026-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0004_alter_profile_department_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
