# Generated by Django 4.2.27 on 2026-03-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0007_profile_initials_profile_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Business', 'Business'), ('Event', 'Event'), ('Finance & Banking', 'Finance & Banking'), ('Branding', 'Branding'), ('Renewable Energy Engineering', 'Renewable Energy Engineering'), ('Energy Business and Technology', 'Energy Business and Technology'), ('Digital Business Technology', 'Digital Business Technology'), ('Food Business Technology', 'Food Business Technology'), ('Business Mathematics', 'Business Mathematics'), ('Computer Systems Engineering', 'Computer Systems Engineering'), ('Business Economics', 'Business Economics'), ('Hospitality Business', 'Hospitality Business'), ('International Business Law', 'International Business Law'), ('Product Design Innovation', 'Product Design Innovation'), ('Artificial Inteligence and Robotic', 'Artificial Inteligence and Robotic'), ('Hukum Bisnis Internasional', 'Hukum Bisnis Internasional'), ('S2 Manajemen Pemasaran dan Keuangan', 'S2 Manajemen Pemasaran dan Keuangan'), ('S2 Bisnis Analitik Terapan', 'S2 Bisnis Analitik Terapan'), ('S2 Inovasi Bisnis Baru', 'S2 Inovasi Bisnis Baru'), ('S2 Manajemen Bisnis', 'S2 Manajemen Bisnis'), ('S2 Manajemen Stratejik', 'S2 Manajemen Stratejik'), ('S3 Manajemen dan Kewirausahaan', 'S3 Manajemen dan Kewirausahaan'), ('Lainnya', 'Lainnya')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='External', max_length=10),
        ),
    ]
